FROM maven:3.8.4-openjdk-11 AS builder

COPY src /usr/src/app/src
COPY pom.xml /usr/src/app

RUN mvn -f /usr/src/app/pom.xml clean package

FROM openjdk:11

COPY --from=builder /usr/src/app/target/ingest-*-allinone.jar /usr/app/ingest.jar

ENTRYPOINT ["java", "-jar", "/usr/app/ingest.jar"]

